# Generated by Django 6.1.1 on 2026-09-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='challenges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='industry',
            name='solutions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='industry',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='use_cases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
