# Generated by Django 6.1.1 on 2026-09-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
        ('services', '0001_initial'),
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('project_url', models.URLField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industries', models.ManyToManyField(blank=True, related_name='projects', to='industries.industry')),
                ('services', models.ManyToManyField(blank=True, related_name='projects', to='services.service')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='technologies.technology')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
