# Generated by Django 6.1.1 on 2026-09-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactlead',
            old_name='message',
            new_name='project_brief',
        ),
        migrations.RemoveField(
            model_name='contactlead',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactlead',
            name='budget',
            field=models.CharField(blank=True, choices=[('under_1k', 'Under $1k'), ('1k_5k', '$1k - $5k'), ('5k_15k', '$5k - $15k'), ('15k_30k', '$15k - $30k'), ('30k_plus', '$30k+')], max_length=30),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='project_type',
            field=models.CharField(blank=True, choices=[('web_development', 'Web Development'), ('software_development', 'Software Development'), ('automation', 'Automation'), ('ai_platforms', 'AI Platforms'), ('erp_crm', 'ERP & CRM'), ('it_solutions', 'IT Solutions'), ('book_a_call', 'Book a Call'), ('not_sure', 'Not sure yet')], max_length=50),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='timeline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
