# Generated by Django 6.1.1 on 2026-09-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_message_contactlead_project_brief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlead',
            name='budget',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
