# Generated by Django 6.1.1 on 2026-09-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_deliverables_service_highlights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('mp4', 'MP4 Video'), ('youtube', 'YouTube Video')], default='mp4', max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='services/videos/')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='services/video-thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='services.service')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
