# Generated by Django 6.1.1 on 2026-09-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_alt_text',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='page_h1',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='service',
            name='page_h2',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_keywords',
            field=models.TextField(blank=True, default=''),
        ),
    ]
