# Generated by Django 6.1.1 on 2026-09-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_delivered', models.CharField(default='50+', max_length=20)),
                ('happy_clients', models.CharField(default='30+', max_length=20)),
                ('years_experience', models.CharField(default='3+', max_length=20)),
                ('tech_experts', models.CharField(default='10+', max_length=20)),
                ('how_we_work_title', models.CharField(default='How we work', max_length=200)),
                ('how_we_work_description', models.TextField(default='Our process is built around clarity, speed and accountability.')),
                ('how_we_work_points', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
