# Generated by Django 6.1.1 on 2026-09-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComradeAIQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comrade AI Query',
                'verbose_name_plural': 'Comrade AI Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
